### ISSUE TITLE
Remove the Energized blocklists for the time being

### ISSUE THREAD

**Issue by GiddyGoatGaming** [dnswarden/blocklist-staging#2]
Currently, the energized lists are going "crazy" and blocking certain very trustworthy domains like nextdns.io and currently has 229 open issues which is concerning. I propose to remove the energized lists for the time being so the server load is reduced due to less rules and maybe add other lists which may be more reliable. More info on what I'm talking about at their github https://github.com/EnergizedProtection/block

**Comment by bhanupratapys** [comment]
I've noticed energized lists going bonkers from time to time. I'll remove energized lists from default adblock and adult-filter dns. People can still use energized lists by using customfilter dns.

As of now there are about 15+ million domain entries in this repo, servers should be able to handle 100+ million entries without any hiccups (as long as wildcard entries are minimal).

Will update here when the changes are live!

**Comment by GiddyGoatGaming** [comment]
Sounds good!

**Comment by bhanupratapys** [comment]
Changes are live!
