### ISSUE TITLE
Is there any downside in wildcard entries for dnswarden now?

### ISSUE THREAD

**Issue by GiddyGoatGaming** [dnswarden/blocklist-staging#31]
Just saw the new update to dnswarden and was wondering if there is now any downside to having wildcard entries. If there isn’t. Il try to switch over some lists to wildcard entries that aren’t already

**Comment by bhanupratapys** [comment]
There aren't downsides now, i fixed that couples of weeks ago. I managed to switch out the most relevant lists to wildcards and left out few like  `oisd (basic)` where it `dbl_basic` and `dblw_basic` were almost same in size. Go ahead and switch them if you find any others. I'm in process of deploying changes to backend and it might take a while to reflect the changes in backend.

Newer version supports this kind of format.
```
    {
      "name": "dnswarden (Tiny whitelist & blacklist)",
      "category": "Tiny, Whitelist, Ads",
      "url": [
        "https://raw.githubusercontent.com/dnswarden/blocklist-staging/main/blacklist/blacklist_extreme.txt",
        "https://raw.githubusercontent.com/dnswarden/blocklist-staging/main/whitelist/tinylist.txt"
      ],
      "filterType": ["b-norm", "white"],
      "source": "",
      "totalDomains": 0,
      "value": 113
    }
```

Where you can have multiple urls to a single value and define what kind of filter it is. 

`filterType` can take 3 values, 

- `b-norm` is for exact domain matching. Eg: dbl_basic
-  `b-wild` is for wildcard matching. Eg: dblw_basic
- `white` is for whitelist.

**Comment by GiddyGoatGaming** [comment]
This is awesome! Thanks
