### ISSUE TITLE
Which would you rather, hosts or domains when adding blocklists

### ISSUE THREAD

**Issue by GiddyGoatGaming** [dnswarden/blocklist-staging#7]
Question. Does it make a difference to you between hosts and domains when adding blocklists to dnswarden. I know with rethinkdns, it doesn’t but I wanted to know here.

**Comment by bhanupratapys** [comment]
It doesn't matter, it can handle both. Domains lists are smaller in size when compared to hosts list, so it takes lesser time to download and update the lists 😬

**Comment by GiddyGoatGaming** [comment]
Ok, that’s the answer I would have thought. Could I make a pull request to switch some big blocklists like hagezi over to domains?

**Comment by GiddyGoatGaming** [comment]
> It doesn't matter, it can handle both. Domains lists are smaller in size when compared to hosts list, so it takes lesser time to download and update the lists 😬

Ok, that’s the answer I would have thought. Could I make a pull request to switch some big blocklists like hagezi over to domains?

**Comment by bhanupratapys** [comment]
Sure!
