### ISSUE TITLE
Blocklist Suggestions

### ISSUE THREAD

**Issue by jarelllama** [dnswarden/blocklist-staging#80]
Hi, I'm the maintainer of [Jarelllama's Scam Blocklist](https://github.com/jarelllama/Scam-Blocklist), a blocklist for newly created scam and phishing domains automatically retrieved daily using Google Search API, automated NRD detection, and other public sources (does not contain other blocklists).

This blocklist aims to be an alternative to blocking all newly registered domains (NRDs) seeing how many, but not all, NRDs are malicious. A variety of sources are integrated to detect new malicious domains within a short time span of their registration date.

If you're interested, more info can be found in my [README](https://github.com/jarelllama/Scam-Blocklist). Please do let me know your thoughts!

In other news, the NoTracking list you have as a source is currently archived: https://github.com/notracking/hosts-blocklists/issues/900

and 1Host is under slower maintenance: https://github.com/badmojr/1Hosts/issues/1307

**Comment by bhanupratapys** [comment]
Added your list in https://github.com/dnswarden/blocklist-staging/pull/82 . Thanks!

**Comment by jarelllama** [comment]
Thanks for the quick action!

**Comment by jarelllama** [comment]
Oh one thing, appears the categories do not match the blocklist.

```
    "name": "Scam-Blocklist (Jarelllama)",
    "category": "Ads, Privacy",
```

I understand that there are currently no Scam/Phishing categories, only Parentalcontrol and Malware?

**Comment by bhanupratapys** [comment]
[Fixed it](https://github.com/dnswarden/blocklist-staging/commit/deb19b7d875d42d993c4150561d0aece5499766a).
